function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "bouncing_ball"};
	this.sidHashMap["bouncing_ball"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "bouncing_ball:10"};
	this.sidHashMap["bouncing_ball:10"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Acceleration Integrator"] = {sid: "bouncing_ball:3"};
	this.sidHashMap["bouncing_ball:3"] = {rtwname: "<Root>/Acceleration Integrator"};
	this.rtwnameHashMap["<Root>/Compare To Zero"] = {sid: "bouncing_ball:10"};
	this.sidHashMap["bouncing_ball:10"] = {rtwname: "<Root>/Compare To Zero"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "bouncing_ball:1"};
	this.sidHashMap["bouncing_ball:1"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Constant1"] = {sid: "bouncing_ball:14"};
	this.sidHashMap["bouncing_ball:14"] = {rtwname: "<Root>/Constant1"};
	this.rtwnameHashMap["<Root>/Digital Clock"] = {sid: "bouncing_ball:20"};
	this.sidHashMap["bouncing_ball:20"] = {rtwname: "<Root>/Digital Clock"};
	this.rtwnameHashMap["<Root>/Ground"] = {sid: "bouncing_ball:8"};
	this.sidHashMap["bouncing_ball:8"] = {rtwname: "<Root>/Ground"};
	this.rtwnameHashMap["<Root>/IC"] = {sid: "bouncing_ball:4"};
	this.sidHashMap["bouncing_ball:4"] = {rtwname: "<Root>/IC"};
	this.rtwnameHashMap["<Root>/IC2"] = {sid: "bouncing_ball:9"};
	this.sidHashMap["bouncing_ball:9"] = {rtwname: "<Root>/IC2"};
	this.rtwnameHashMap["<Root>/Multiply"] = {sid: "bouncing_ball:15"};
	this.sidHashMap["bouncing_ball:15"] = {rtwname: "<Root>/Multiply"};
	this.rtwnameHashMap["<Root>/Scope"] = {sid: "bouncing_ball:12"};
	this.sidHashMap["bouncing_ball:12"] = {rtwname: "<Root>/Scope"};
	this.rtwnameHashMap["<Root>/Terminator"] = {sid: "bouncing_ball:11"};
	this.sidHashMap["bouncing_ball:11"] = {rtwname: "<Root>/Terminator"};
	this.rtwnameHashMap["<Root>/Terminator1"] = {sid: "bouncing_ball:22"};
	this.sidHashMap["bouncing_ball:22"] = {rtwname: "<Root>/Terminator1"};
	this.rtwnameHashMap["<Root>/Velocity Integrator"] = {sid: "bouncing_ball:7"};
	this.sidHashMap["bouncing_ball:7"] = {rtwname: "<Root>/Velocity Integrator"};
	this.rtwnameHashMap["<S1>/u"] = {sid: "bouncing_ball:10:1"};
	this.sidHashMap["bouncing_ball:10:1"] = {rtwname: "<S1>/u"};
	this.rtwnameHashMap["<S1>/Compare"] = {sid: "bouncing_ball:10:2"};
	this.sidHashMap["bouncing_ball:10:2"] = {rtwname: "<S1>/Compare"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "bouncing_ball:10:3"};
	this.sidHashMap["bouncing_ball:10:3"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/y"] = {sid: "bouncing_ball:10:5"};
	this.sidHashMap["bouncing_ball:10:5"] = {rtwname: "<S1>/y"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
